### ISSUE TITLE
Bug with offline energy production 

### ISSUE THREAD

**Issue by jepstein30** [sparticle999/SpaceCompany#102] opened 2017-06-17 04:03 UTC
Can't nail this one down yet but my energy production seems to reset to 0 every so often when utilizing offline progress. I think it happens when it hits the current max storage when offline but I have to continue testing.

**Comment by jepstein30** [comment] 2017-06-17 05:04
Definitely something buggy here. I loaded up the game after an hour or so, more than enough time for everything to max out, and I came back to everything max'd but energy starting at 0. It does seem to be related to hitting the max storage, seems like when you do max out when offline, it starts you at 0 when you come back.

**Comment by sparticle999** [comment] 2017-06-17 07:31
Thank you for checking this

Sparticle999

**Comment by scriptsforweirdos** [comment] 2017-06-21 16:52
Same issue here using Waterfox on the Kongregate version.

**Comment by sparticle999** [comment] 2017-06-22 18:46
Can you give me a savefile/screenshot/video?

**Comment by scriptsforweirdos** [comment] 2017-06-23 01:30
Savefile, just saved after loading. Energy was full when I left yesterday. 

`N4IgbgpgTgzglgewHYDkCuBbARtEAuEABgDoAWMkAGhABsBDGAFwDE4APCAEwFUAHTuowj4AjKQCcADhHSAzADYA7IoBMAVmq96MDHXzzJ1ABYRBuPIWOmhUAMq86AYwgBZCIzo0Awgib5FaoRBVmZQAOIQGD5+eAZBliAmobZwNHCOyNGM+Gri8SE2ACoIAOYlNFz4jFBoEJrauozp+AlaDI3p9k6u7p5Z+NLxrQ2Cnanpmb7ZeKpD9e2jjm5CCFBwQv144orDC02OxWUVnFU1dSAQSNAlAJ6iipKyJJIqsuLvH1LUWII2d3gqb6/aA3ZZ9Kb6QiBBI/Rh/CJRCGxKHBECwv5dZxg7xIhRPGHAqA3QoqFpAuEgknYzZqaGo9GUlQIml0gkUokkzE9Dw4mKyfGoxxGOhQDKeACiSBKcCu+BUCSFIrFNEl0qu1NxCmoitFCAlUplEGZSJEBm1wt1+rVEAA8mhGLx7fhSNQYAh6FAAAp0K40HLiV3ukXe30amKPQgukBuj0hiA0Y0xcQGQzRoNen3xu0Op14WTUDDuYVXWweJrIOUaECFxjFiCl0bILlh6YiETiEQFouZhvlpCFdY+uCYTbbKtINCOCoi3uIJD4fMgCdT0x2Mtz5u9XnTFTyeTy6jL6drxv9wdIYeImIifkiBK6EodRxygt0R+LTc8zZPdT3t9PxNpjxVEHyfFIaEgKBNhUUh5QSAAzNB4GQAAlUxHEYVZnWoRDkKQNCnEwuwHCxLdNlIN5XhwpC5wIjDVgHDwLxHJEVHEFQXmovC6KI8CJiQaD23kTsQAQVJREIGDUTEmhS1WN9hDwO8pISGSUAgNhGDkqAFLlSNJFRR0MF4CTNEwXgW1EWkzOMwCchEozeAAKycABrAYbOctzLLwSR5EXRyXMcVy7IBcQAvMoLXJtVJNhEVRPKi7NHVbVTUlYeMTiU6gZIymhOE/cEYl3Ug0poPLOEYocWOK7YyoqviMgEpFYLyHLUhQuASjJUSOq6wrt1EcRSrKzqSiq5ir1bOJRq65YIFWdYIE2RR5HvLc9NIAz1p5bTdIBfSQK3dTNL2kpFNK5MQMNKBTOrG6fPUAsboAdQQBBODiwFElMMAbgAETWGg/TwKskj+wHUhoHzAm+8GAaBhNIjiyRU3hyHgZiwalLUeQQghxHktzU1qGlEo6AxkGRLJinEYG79CAM0mutpqHQtkRRSuZ8nKcayYYlINQ72oABHNAfUYTBKZ6sWJalumSO5IqdzyVFZaQSWMEpsJ3U+k1JB2BJ1c1yn5sWjYkVV0nIgklTrYwM7FOUkb7ZOrSiP2+UttRc6MBcG67t9/2rigHzZFTIObtCp6QDoTgwB9ZxOGlnHqDjhOkCT02yJNQhObT+PE64bXkZNRQ2tjwvM+LwnYqRNQOYLjOs8J+0Uo8kBODgOgMGQZPEdEagu57vvecVsPOYSYfe6Qfu2dL8NtqH7uZ7n4G+eagXxECbURSwG4rhThU94PiAx+6R670FE/D8R6PDePqB99vqGzbWC3w0FC1lVtl2QB1ZUjtf5fyVHqGgbsgEHW9gqb+YDDjlEqHgaotRqAAHd3qcCwGgKAIc7roI+lgnB0BHpVnwZg7BIc3ofS+tRHB3RRDfUQnQ0iX5WJC1oUgboVC9bXhjkwzhzgsbfhvBwrhGCACSSB25KUYRQ7oRNpiplcqkecFhqDKJoEgemuJoTqJUaFfcqINFaPGE1b8S8QDwSJOYBC1jiIXxzteNQFirE3GgAAGToAnL6ujLF2LfktGka00EYOAQkMhkDnaojIRAj251NoWLIY4e0Ng8EYOSeyHy0gQkfQyTYbh5EEjaGgF4FJ5gVAiWKVBMpodHFAR2NQKppT2QGL3I0hgJSalCNYsmdpMBOnsgUQwoeEB4KrAgEwGxIyxlQAmTYbRfJ8id1GeMyZUAJqXmgobaZqz5mmP5juXxMpcJTJAMcpC0AFnTSWec/pUBul8hEHBagtziHuAWu/ZaLUK4wEcHAS4zgBilXkLkWQxB2zsSCG8dpWA9IwoKUiJQMLQpXxhT5G8UZ6BYBJC+WgdBsUqARTENaVYsUkmjrBGFVI6kMOFni7Fsh9BUtkES1shs8b0sKLIUKjxdzMrDoQNsHKoAIGCu4HqIqxUsFqCDR4TziC7gbhxIIQlqCStcu4ZgMr4HHHwPBTw/TzSRHSJ4T09ANa4qFMaxwprzWMHRRUmB1rbUS1CnkRQRqMAmpoGaiWDzpgkpymwOAXcYCnh6ggYNobTwOqWZGkNcAw19h5fiINCak1zn9foCxMBx4bSUpJP+uaHG7TiU7QtqJi0sM8LE+S8SoEWJrHWBhjbuwljLS2o6tZMy1p0vW9Qa0EhNCYpeeyzyQDDuqg7DtoMnmoknZNXt+0okJBKLrMdPtdaQKFuOtd+Ul31pXa6VIkEN0JHgBBS5M6d2VpPdAA95a7bRn2aoo9z60hNUiRW89L6H0JJAu9JAb0oAatulsAsgHgOgZRfFVMvdkAp0XPBpA2dWHFUkA3CDCG74LzZW2LDKHa7YzbKQESyGACK4soBElxRRqjRIrn4GTEzasgHKMiiJAYlEBH2PUZuBvcirwqxtCuIwcUbAbUJyIj1ET7hxOScEAxc8myWp0nmKJ+TXjFNQHEc4b8D91NyYk1poiASP7TF8QnZJmA5RRis2gTAjG8ASG+vZzAoUXNRhgJOPsmmpNYSUhy7zGE5x+e005yerofOheM/58IuH/QHmjNF5AYWiJZuc6QLm0ZFY+FQYPHL3Q8tOZKue3LCBUEbJqirBphW9MVYEy1NiCRIAWrUeAS4Wk81oYs3BFrnWAAS8YVMCwMx1jWZmvl8grhpLQ4ywNRlmzQebKLSDyC891zwiHXSbZoOfat2Nw4Bjq0rPbOGppWWcTtktW2iNxWGqmXgnXWbA1xU9jWL3ZK7bivIYarRnslwu0pW8/2Pu8xfZsJQq1qALqPjD88+3TuQ4FPDpi2tdZbKWbDxGk3Ieok4CKkNwzO6E4Kt9xFKgPUk7EpwZYdY4q4xGUwEVbiFtM+qAgVnTmDJVk4HMln0AKUiF5/zzn0AMumjpXzwQRgGxgZEtL2scunMyG2csmXyu71QRNIqqe1hZceDsBDy2kkEiEXFtJ9r5vwvk+JVfM3GELerCG2karVk1fW9M+882U2A2VoyLmb6vyED2hVxU10AfGBVaBzBa7zhPF3IXHHiACfLm2+mGtqsVaU8dPi0Dts2xk+p/uXXJxhe0TQG7QVnAUBu0lbEDvCvtfhTR+gkEJLNe6/G94ai/+PokAVnazapAA+tHp4GELa+I/kAZfChY4fo/cf1w78t1BREhRJ7RKv9fsvx9KXeN8bfqwhSt9xMd4PooTBgaCxkS/aebvEdgxH4/V/o4vHP7fq1JfDvKG+v3uARgqQ2mBW/+gB9AvEe+/IqIoBQBREbqN4ZuI+ABsBqw4EkE0E62eudy0wWBleJWcwyy2BjW14yg+OEyleS+AsqIsy/SSoRg3ASAy2YqWUyC5wNBq4VqWUAA2iAGgIwaKq5AAEIMDpCSjXB3DUB8FMGuRAKSH8HBRYxUC8HyEyHphKFSECEuBOCAFXAwDqG8AlA6R85oRujYLOCFAQAb5yHSH/T84pbzjWECG2Dpi2A3CTIYDqEqGeIEr6GGFxwQCqiGgWFWG8EGFGH1jpjBFGCeHSHeFcoxECHCHsj/J6GOHBQoQCGaraqkhpGuS+o6B6C5HigYDPi5H5G6ADjQA5HKHSGTYJHBSTaVFQAiD1GuSNH/JQDVEaHBRJE2ApE4oAC6acCcQBWAFQ+APB3RMhHauRwh8AjgYhUAtwrRzhHorRWhQohoqRoRfhfOgRVwURrRihkhYR/hqxIohxuR5xdgbhQgHhJxuxEAJhIeooEAlxNRAhthzO9hrRcRXRKhGRUqWq8YOKuRcRjKsxhIKRrRvR0A/R/x0h5RhRHxwUSJTRCJAhxRpRKJbR3uny6xeJS0TRLRuR7RVRIAQxE6+KMADB0hiCPB7BdBhQ+KShMYM4txkQzJsKISs80AXJFJaqEyLxzgNJKh9JFwIctwKAXiShACYC0pYAShakMp2o7o9AvA/SkiIcvqomrJu2CpShTamYnoFWuAXY3aVwBpqOU6Vp76/Etpe6nAtpF6kEtpDIawEyShlw4hjsghkaspapdAGpto9o0AOp4qXEc4JpqCZpiQNwBOpQlwtpJgruGAtp6QEAzp7oXgnWsZMYOZGsfJCAvA/JaqmR0qIJ1RvAsyfyIeMAb0vJUAtp6CjZzAy2qwIgtp2CNpKpS4k4x40ZsZ3pSx7g6QDZfOTZvZ9ACctpoEiwg5t0MOlhRg4596vZbQBRtpkQjg3o8S8wBR6JhphJQgs5x5ARLgXgR5KwnyxJV5HyRJHR1R7p8JApS4CAfpUAE5ExEp4hBplJ6q7gnifBnBpwKCE6y5tJmRLBZw5p95QgkFzBeqBq5wWCcIyAMAA2IafOqiPBS24yLggGXpbAc2syAAapcEhERSRa4CKNsXhbMgAIJrI06CHxjZDUD0UQCrknh9hUXLazIABSaAvAS0i5FwxF/F9YggFCfF4yZq9oCAslsyAA0mgHAE9lAKxTQOxeJdRasQWakpoDWYgEhJ6CKoYRMtsdWZYSZfWX3NAIISkhWGnCFlJhAGZTZXWdxV6ZKaOTueZTQXRb5fsNxY5WhQ4bHK5WYIsedCFfZWJUIEKGZaUIFUoYlSufFWFZhBFYRHAG5VEd5YKbQZfkiUoYyZflia+Zxdwaxs5eNpRa+LAEoQwDYCxWxUoS2RObOHVU5MJaJaydJTgkoVoApUoa5GpRpVpTpfmbmbdJSd2ZNKIIOpITpJNJEstbwatZeH+nmOOrlW5TVdZbWQ1T+SOfsGlcua+YYTKF+QCKTGsI2afsVLBKug9V1XvltNltdY2TrPlNBC9dqGgFgM0Hdf/EDekNwFtW7lsBysksDY4GHr3nDekBLo6gkJcGsF/j1BjekFfvXmrjjV/k9TuCjhKZjXjd3q2LIL4jWTcCuGBgkLTfTU5uFL3kzRULUhab7s6GNuzW8teYEkiBGO0gnM6KiNOXQJAn/BLTtfPjUH8mMYpFWI4PLXAIrU5utpSv/KrYrTBpTouBpNUIRAFgbZpDpPRPYgdijP5ItmbcbessptDcLtsN9IbebbxJTf4FIBym7WgLdejWbX7fflbYiqrAHcghOcTTkGNr7V1Z7XmGHdQJADQMJZLMAe1snanU7pbUjj0ttP1inbwGnXARjjrvbknfGFndppQdMAEAkEYPGeZZcEtaiA3QmedFojOqaK3Y3YmagIbZArIOOhkMDJYZbt9CPRUBbRFruAqGqWPUpiOtDc4ozK+CULqdlNWG+KJirooG8Ehtve4FHTjGtn+Ove4L9TwqlPuMdstPGCDK7TmevFruRIEE8hxU/QmKXQLDeJxBcJ/cQUBE8jIMYDdZcIQt1O1jodhRA7vX1qA7yUgBA3TpmHFLICNPXWA0g9giUDXf4HSimaOr5K3cNo5jOhYoQ5gDtd3VPCKrKKDQmSWHvneKaFGIw/WPHaoMElSUgKBj1ExKBirlDkOj6KBsfTeGoNDjw4I/HW2DIHPcZIFQFiJBkIo5ZagXvr9qmv/AgGozAG6A7UvUDltPI6qXowY4AwuJIH9q6MohgIWAzbY3APY8HbncVLSEsjAHYw4+I3vZ494/zXBdzTMLVhmXpAkBmZAuOhmTtX/BmZ6OkO5JvfE4kyrtvCxik8FNHE8k8C8s4HDmcvkwrA/tBG8KiBmZTMfRUtE0U1DJY/vhtVYhABAAAF6nJNOtOuPorxRLIdNtOGNTqbB+S9OzKdNG4foHL+Ck0YBQDMCjNtM9QzNzPNNtOsoLjlxLJLPzMQAu4jatgYMFizPbN4M4xdpBM5A7RBPbqXM+7UNnM+46qIKsFGUyipLtbVmvNdM0oFoEEfOFnjP8Q0gEExmwrtYgss0CjhIQBYCQ2DPfLAvQv1OT5LKcBuGD5TxotnhGMMwEGotuhICX1xRDAYv4v1N9b46YsnPl2dyYu6bBP26Vq8BX6KTnqoIigeHtYPWQMO6AEQCQCFgax6F4CgCQR4TYQSnVDQnCuRVGAAD6hAuK2hsrLRoNSrpIqrQosrjKGrcrpAm+Sragirmr8gIBmrigRrcrkgprcr4gFryrCrOryrKrf+mrTyPUSrN47rrrerVurrhrvrcrpoXrgb5rAbyrVrYb7Y1rsr8owbMbJrYblOcbTwybKrPLWrPr6b1NybEbWbtrYbsEcbFERbob6bzicbuQcb+4cbfkcb7ELQAAvg266OuEwOkEKyK9AGK5vZ1h6R21vROJ4M8WYZ6dK4qQCJTknXoBO4oM2xOh0TaKglcJwCqyK/oFWKLbEGoHO00OLku1wOq2uzMFO/4Duwu/u5wNq0e8dpu+IGe3u8uz60e65tOyoPe/che/60eyJJuyIO+4u8uwm8+yewCDu9SQhRqllEe3ZtO6QHOzQcKRMhB4gkexypu/IDu8uSYRwSYFB+ADkCB9u/MCKeJtRXh+OzB86HO51V245akNMEe4uJu7INR/FTAAxVFUIOR7ipu2+66JZXOAOIWPgEew8CQKQOXPuHuHIE8KmJu2J2QJJ7uAYDeLJ2e4WL6m4txzMAZIp8mMpzJ6veANOwpxJ/p9J6p4zHOzMo0G89GEYKsIwNKcJ98LrJKPirqngPqjQIas+nzj8NruY4gt575wPk0PBCan2DAO54rdBWBbWJEIpGiB0s1QpbYF4hAJIjYAnCDJC020VYh/2+O1WGBqAMOcsdK6ogkGgEhT5xAHOxuboCJ0uD1DV158hXOwtUQ6AFV5IbV/0nOxLc1717wf1/V+1CDD1612N3OzWJ4MN9N0gmcHO77At+1m16wXO3KfN5V4tyF+NyAGQmt9V6BQdxevxMd31+13V3O9ntiJd6N9dwN+ac2rt+tzN9aYtW9yd09wd46Q921/t7d1rgDx93Ge3c3d91d0D1YKmaD793O2E1D49zD9WGefD6j78v8tXBjx1/l2iGpflDKCUEVwVnAM1+V8SGmxxZKcSOq+jbT/Ee1pT4UJmzT+IYUP6wzxzwm7sAedTyAI13QDiut1DRgIUAL115gCL9V2L0z7L1Oqzz1BLRL8r1pjLyLcL9q0Uur2z71DQKr+1jJBr/r/LxN0r+1nNwbwL1byb7b9r+aZ4Bb6upyQL77Cb+7w7yAO73r9t9bz1H7yb4H174H3r2Qob+Ehgib+H17+H3r+d01BH8ehM/2PT8n/xGb3aYn/H7tknydtiCb3d1uJn0XzyM7y95mHn0aQcWn2j1zZn9X28XrwupeHny39L7X+3+L1713+X977rHn46R7wP170P/H1rnny6XybX1P+sl77P3323U3f2AL0v33Sb2vx3Zn5v5cIv6Q+L6v/vxv0f175Q+L3rxmXn5f7X5f175f3rzWEE1X2eYX38gCm8QL1j+/6/9j+YV7wBRWX96ctyywJA3vT3x7pVmu47ESOT2lZMA60EAPgI8VKrtZ4BfaRAacT5ywsvu56MtEgPCKeJN2uAhAfgP8KKFUBeAzAadh6hoCFIpAvnAiBoGUDHiXgWBDt2IHoD6BXFUJBQJIFUCN4TAvgY8QGiCDOBVAlBvQw4F0CqB0eUQdIMeKX05B50LgWgVOS0DlBVAgbL3Q7pKCMBjxXZjZl4FiDHidLXQVwLqLrcVCcxUQrT1a4qEsYyVEUvAClB2DpC1xVwQIWHavENiOhUdtVxUJfFkEIWdFlcRcIckOW/g2IvihN5TFPEJZL3lMVhIchJeVgwkHTw8GokRgefKYmiVr5TFKqlg2oi/xSFFCBaQgGISoUaIJCAhmLWwGyygARDci/0WoUy2gAssHi4RLweYUurrcqB+xN4j0Oq78DIigwjivBAi5v9M4NwbDnQTlAsdbu7gJoFKCK5ds5wBWXtlK2ABNsG2QAA`

**Comment by scriptsforweirdos** [comment] 2017-06-23 01:33
Also noting for the record, my energy had regened from 0 to about 40k by the time I exported the save.

**Comment by Brilliand** [comment] 2017-06-24 22:25
This also happens with Plasma, when I log out with negative plasma production due to meteorite production.  My plasma production is positive when I load the game (because the meteorite capacity filled up), but my plasma quantity is zero.

EDIT: Looking at the source, this is a different problem.  The energy problem is caused by applying the energy cap to each individual thing that produces energy, instead of after summing the production/consumption rates.  The plasma problem is caused by not updating the production/consumption rates partway through offline production.

**Comment by Craiel** [comment] 2017-07-07 17:57
Should be fixed now with 0.4.4.4 Beta

**Closed as completed by Craiel** 2017-07-07 17:57 UTC
